// === รายชื่อตัวละคร + รูปจาก api.hakush.in (อัปเดต 2025) ===
const genshinCharacters = [
  { name: 'Albedo', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Albedo.webp' },
  { name: 'Alhaitham', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Alhaitham.webp' },
  { name: 'Arlecchino', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Arlecchino.webp' },
  { name: 'Arataki Itto', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_AratakiItto.webp' },
  { name: 'Baizhu', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Baizhu.webp' },
  { name: 'Barbara', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Barbara.webp' },
  { name: 'Beidou', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Beidou.webp' },
  { name: 'Bennett', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Bennett.webp' },
  { name: 'Candace', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Candace.webp' },
  { name: 'Charlotte', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Charlotte.webp' },
  { name: 'Chevreuse', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Chevreuse.webp' },
  { name: 'Chiori', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Chiori.webp' },
  { name: 'Chongyun', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Chongyun.webp' },
  { name: 'Citlali', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Citlali.webp' },
  { name: 'Clorinde', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Clorinde.webp' },
  { name: 'Collei', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Collei.webp' },
  { name: 'Cyno', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Cyno.webp' },
  { name: 'Dehya', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Dehya.webp' },
  { name: 'Diluc', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Diluc.webp' },
  { name: 'Diona', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Diona.webp' },
  { name: 'Dori', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Dori.webp' },
  { name: 'Emilie', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Emilie.webp' },
  { name: 'Eula', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Eula.webp' },
  { name: 'Faruzan', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Faruzan.webp' },
  { name: 'Fischl', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Fischl.webp' },
  { name: 'Flins', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Flins.webp' },
  { name: 'Freminet', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Freminet.webp' },
  { name: 'Furina', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Furina.webp' },
  { name: 'Ganyu', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Ganyu.webp' },
  { name: 'Gorou', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Gorou.webp' },
  { name: 'HuTao', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Hutao.webp' },
  { name: 'Jean', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Jean.webp' },
  { name: 'Kachina', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Kachina.webp' },
  { name: 'Kaedehara Kazuha', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_KaedeharaKazuha.webp' },
  { name: 'Kaeya', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Kaeya.webp' },
  { name: 'Kamisato Ayaka', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_KamisatoAyaka.webp' },
  { name: 'Kamisato Ayato', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_KamisatoAyato.webp' },
  { name: 'Kaveh', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Kaveh.webp' },
  { name: 'Keqing', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Keqing.webp' },
  { name: 'Kinich', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Kinich.webp' },
  { name: 'Kirara', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Kirara.webp' },
  { name: 'Klee', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Klee.webp' },
  { name: 'Kujou Sara', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_KujouSara.webp' },
  { name: 'Kuki Shinobu', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_KukiShinobu.webp' },
  { name: 'Layla', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Layla.webp' },
  { name: 'Lisa', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Lisa.webp' },
  { name: 'Lynette', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Lynette.webp' },
  { name: 'Lyney', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Lyney.webp' },
  { name: 'Mavuika', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Mavuika.webp' },
  { name: 'Mika', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Mika.webp' },
  { name: 'Mona', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Mona.webp' },
  { name: 'Mualani', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Mualani.webp' },
  { name: 'Nahida', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Nahida.webp' },
  { name: 'Navia', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Navia.webp' },
  { name: 'Neuvillette', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Neuvillette.webp' },
  { name: 'Nilou', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Nilou.webp' },
  { name: 'Ningguang', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Ningguang.webp' },
  { name: 'Noelle', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Noelle.webp' },
  { name: 'Ororon', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Ororon.webp' },
  { name: 'Qiqi', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Qiqi.webp' },
  { name: 'Raiden Shogun', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_RaidenShogun.webp' },
  { name: 'Razor', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Razor.webp' },
  { name: 'Rosaria', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Rosaria.webp' },
  { name: 'Sangonomiya Kokomi', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_SangonomiyaKokomi.webp' },
  { name: 'Sayu', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Sayu.webp' },
  { name: 'Sethos', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Sethos.webp' },
  { name: 'Shenhe', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Shenhe.webp' },
  { name: 'Sigewinne', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Sigewinne.webp' },
  { name: 'Sucrose', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Sucrose.webp' },
  { name: 'Tartaglia', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Tartaglia.webp' },
  { name: 'Thoma', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Thoma.webp' },
  { name: 'Tighnari', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Tighnari.webp' },
  { name: 'Traveler (Anemo)', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_PlayerBoy.webp' }, // แยกตามธาตุ
  { name: 'Traveler (Geo)', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_PlayerBoy.webp' },
  { name: 'Venti', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Venti.webp' },
  { name: 'Wanderer', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Wanderer.webp' },
  { name: 'Wriothesley', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Wriothesley.webp' },
  { name: 'Xiangling', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Xiangling.webp' },
  { name: 'Xianyun', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Xianyun.webp' },
  { name: 'Xiao', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Xiao.webp' },
  { name: 'Xilonen', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Xilonen.webp' },
  { name: 'Xingqiu', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Xingqiu.webp' },
  { name: 'Yae Miko', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_YaeMiko.webp' },
  { name: 'Yanfei', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Yanfei.webp' },
  { name: 'Yaoyao', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Yaoyao.webp' },
  { name: 'Yelan', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Yelan.webp' },
  { name: 'Yoimiya', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Yoimiya.webp' },
  { name: 'Yun Jin', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Yunjin.webp' },
  { name: 'Zhongli', img: 'https://api.hakush.in/gi/UI/UI_AvatarIcon_Zhongli.webp' }
];

module.exports = genshinCharacters;